apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.gcs.hmacSecretName }}
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.gcs.vaultStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.gcs.hmacSecretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: OBJECT_STORAGE_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.gcs.vaultPath }}
        property: OBJECT_STORAGE_ACCESS_KEY_ID
    - secretKey: OBJECT_STORAGE_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.gcs.vaultPath }}
        property: OBJECT_STORAGE_SECRET_ACCESS_KEY
    - secretKey: SESSION_RECORDING_V2_S3_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.gcs.vaultPath }}
        property: SESSION_RECORDING_V2_S3_ACCESS_KEY_ID
    - secretKey: SESSION_RECORDING_V2_S3_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.gcs.vaultPath }}
        property: SESSION_RECORDING_V2_S3_SECRET_ACCESS_KEY
