apiVersion: v1
kind: Service
metadata:
  name: {{ include "posthog.fullname" . }}-capture
  labels:
{{- include "posthog.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "posthog.fullname" . }}-capture-bc"}'
spec:
  type: NodePort
  selector: { app: {{ include "posthog.fullname" . }}-capture }
  ports:
    - { name: http, port: 3000, targetPort: 3000 }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "posthog.fullname" . }}-capture
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.capture.replicas }}
  selector: { matchLabels: { app: {{ include "posthog.fullname" . }}-capture } }
  template:
    metadata: { labels: { app: {{ include "posthog.fullname" . }}-capture } }
    spec:
      containers:
        - name: capture
          image: {{ .Values.posthog.captureImage | quote }}
          env:
            - name: ADDRESS
              value: "0.0.0.0:3000"
            - name: KAFKA_HOSTS
              value: {{ .Values.kafka.hosts | quote }}
            - name: KAFKA_TOPIC
              value: "{{ .Values.kafka.topicPrefix }}events_plugin_ingestion"
            - name: REDIS_URL
              value: "redis://{{ include "posthog.fullname" . }}-redis:6379/"
            - name: CAPTURE_MODE
              value: "events"
            - name: RUST_LOG
              value: "info,rdkafka=warn"
          ports: [{ containerPort: 3000 }]
          resources:
            requests: { cpu: {{ .Values.capture.resources.requests.cpu | quote }}, memory: {{ .Values.capture.resources.requests.memory | quote }} }
            limits:   { cpu: {{ .Values.capture.resources.limits.cpu | quote }},   memory: {{ .Values.capture.resources.limits.memory | quote }} }
          readinessProbe:
            httpGet: { path: /_readiness, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /_liveness, port: 3000 }
            initialDelaySeconds: 30
            periodSeconds: 30
