{{- if .Values.tls.vaultEnabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.tlsSecretName }}
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.tls.vaultStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.tlsSecretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ `{{ .crt }}` }}"
        tls.key: "{{ `{{ .key }}` }}"
  data:
    - secretKey: crt
      remoteRef:
        key: {{ .Values.tls.vaultPath }}
        property: crt
    - secretKey: key
      remoteRef:
        key: {{ .Values.tls.vaultPath }}
        property: key
{{- end }}
